### ISSUE TITLE
Non-version folder name in .../iOS DeviceSupport causes crash

### ISSUE THREAD

**Issue by andersblehr** [toineheuvelmans/xccleanup#1]
I installed the gem and tried to run it with the manual option on my machine:

```
...
--------------------------------------------------------------------------------
                             REMOVE DEVICE SUPPORT
--------------------------------------------------------------------------------
Found versions:
• (null) ((null)) (0.0 B)
• 10.1.1 (14B100) (2.9 GB)
• 10.2.1 (14D27) (2.9 GB)
• 8.3 ((null)) (0.0 B)
• 9.3.5 (13G36) (1.0 GB)
> Miminum version to KEEP? 9.3.5
/Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:208:in `initialize': Malformed version number string (null) (ArgumentError)
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:199:in `new'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/version.rb:199:in `new'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:151:in `block in remove_device_support'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:148:in `each'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:148:in `remove_device_support'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:389:in `call'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:389:in `block in run_steps'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:383:in `each'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:383:in `run_steps'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:445:in `menu'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:458:in `<module:Xccleanup>'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/lib/xccleanup.rb:7:in `<top (required)>'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/ablehr/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/xccleanup-0.3.2/bin/xccleanup:3:in `<top (required)>'
	from /Users/ablehr/.rbenv/versions/2.4.0/bin/xccleanup:22:in `load'
	from /Users/ablehr/.rbenv/versions/2.4.0/bin/xccleanup:22:in `<main>'
triton:dev $ 
```

Turns out I have these folders under `iOS DeviceSupport`:

```
triton:iOS DeviceSupport $ ls -l
total 0
drwx------  2 ablehr  staff   68 Aug 27  2015 (null) ((null))
drwxr-xr-x  4 ablehr  staff  136 Mar  8 16:43 10.1.1 (14B100)
drwxr-xr-x  4 ablehr  staff  136 Mar 27 14:51 10.2.1 (14D27)
drwx------  2 ablehr  staff   68 Jun 15  2015 8.3 ((null))
drwxr-xr-x  4 ablehr  staff  136 Mar 10 11:17 9.3.5 (13G36)
triton:iOS DeviceSupport $
```

The first one – `(null) ((null))` – is the culprit, causing the string `(null)` to be passed to `Gem::Version.new()`, which crashes the gem.

It's probably a relatively rare corner case, but there's other mentions of it on the interweb, for instance in [this](http://stackoverflow.com/questions/19187857/processing-symbol-files-in-xcode) StackOverflow thread. I have a fix ready and tested, will post pull request shortly.

**Comment by toineheuvelmans** [comment]
I've merged your pr and pushed a version 0.3.3. Thanks again!
